/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Driver;

/**
 *
 * @author tanujamahajan
 */
public class CreateDriverJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDriverJPanel
     */
    
    Driver driver;
    
    public CreateDriverJPanel(Driver driver) {
        initComponents();
        
        this.driver = driver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDriver = new javax.swing.JLabel();
        lblDriverLicenseNumber = new javax.swing.JLabel();
        txtDriverLicenseNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 51, 255), null));

        lblDriver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriver.setText("Driver Details");
        lblDriver.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 51, 255), null));

        lblDriverLicenseNumber.setText("Driver License Number:");

        txtDriverLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverLicenseNumberActionPerformed(evt);
            }
        });
        txtDriverLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDriverLicenseNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDriverLicenseNumberKeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblDriverLicenseNumber)
                        .addGap(35, 35, 35)
                        .addComponent(txtDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(941, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblDriver)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDriverLicenseNumber))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(488, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDriverLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverLicenseNumberActionPerformed

    private void txtDriverLicenseNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDriverLicenseNumberKeyPressed
        // TODO add your handling code here:
        
        char driverlicensenumber = evt.getKeyChar();
        if(Character.isLetter(driverlicensenumber) || Character.isDigit(driverlicensenumber) )
        {
            txtDriverLicenseNumber.setEditable(true);
        }
        else
        {
            txtDriverLicenseNumber.setEditable(false);
            JOptionPane.showMessageDialog(this, "Please Enter Valid Driver License Number.");
        }
    }//GEN-LAST:event_txtDriverLicenseNumberKeyPressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        driver.setDriverLicense(txtDriverLicenseNumber.getText());
        JOptionPane.showMessageDialog(this, "Driver License Number Saved.");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDriverLicenseNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDriverLicenseNumberKeyReleased
        // TODO add your handling code here:
        int number = txtDriverLicenseNumber.getCaretPosition();
        txtDriverLicenseNumber.setText(txtDriverLicenseNumber.getText().toUpperCase());
        txtDriverLicenseNumber.setCaretPosition(number);
    }//GEN-LAST:event_txtDriverLicenseNumberKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblDriverLicenseNumber;
    private javax.swing.JTextField txtDriverLicenseNumber;
    // End of variables declaration//GEN-END:variables
}
