/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Doctor;

/**
 *
 * @author tanujamahajan
 */
public class CreateDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctorJPanle
     */
    
    Doctor doctor;
    
    public CreateDoctorJPanel(Doctor doctor) {
        initComponents();
        
        this.doctor = doctor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDoctorID = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblInsuranceCovered = new javax.swing.JLabel();
        lblOfficeHours = new javax.swing.JLabel();
        lblOfficeAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDoctorID = new javax.swing.JTextField();
        txtEducation = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        txtOfficeHours = new javax.swing.JComboBox<>();
        txtOfficeAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtInsuranceCovered = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText(" Doctor Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 51, 255), null));

        lblName.setText("Name:");

        lblDoctorID.setText("Doctor ID:");

        lblEducation.setText("Education:");

        lblSpeciality.setText("Speciality:");

        lblInsuranceCovered.setText("Insurance Covered:");

        lblOfficeHours.setText("Office Hours:");

        lblOfficeAddress.setText("Office Address:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtDoctorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDoctorIDKeyPressed(evt);
            }
        });

        txtEducation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEducationKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEducationKeyReleased(evt);
            }
        });

        txtSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialityActionPerformed(evt);
            }
        });
        txtSpeciality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpecialityKeyPressed(evt);
            }
        });

        txtOfficeHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 to 17:00", "17:00 to 1:00", "1:00 to 9:00" }));

        txtOfficeAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOfficeAddressKeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtInsuranceCovered.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        txtInsuranceCovered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceCoveredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOfficeAddress)
                            .addComponent(lblOfficeHours)
                            .addComponent(lblInsuranceCovered)
                            .addComponent(lblSpeciality)
                            .addComponent(lblEducation)
                            .addComponent(lblDoctorID)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtDoctorID)
                            .addComponent(txtEducation)
                            .addComponent(txtSpeciality)
                            .addComponent(txtOfficeAddress)
                            .addComponent(txtInsuranceCovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(959, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorID)
                    .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEducation))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpeciality)
                    .addComponent(txtSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsuranceCovered)
                    .addComponent(txtInsuranceCovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfficeHours)
                    .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfficeAddress)
                    .addComponent(txtOfficeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialityActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        doctor.setName(txtName.getText());
        doctor.setDoctorID(txtDoctorID.getText());
        doctor.setEducation(txtEducation.getText());
        doctor.setOfficeAddress(txtOfficeAddress.getText());
        doctor.setOfficeHours(txtOfficeHours.getSelectedItem().toString());
        doctor.setSpeciality(txtSpeciality.getText());
        doctor.setInsuranceCovered(txtInsuranceCovered.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(this, "Doctor Details Saved.");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtInsuranceCoveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceCoveredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceCoveredActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
        {
            txtName.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter a valid Name");
        }
        else
        {
            txtName.setEditable(true);
            
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtDoctorIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoctorIDKeyPressed
        // TODO add your handling code here:
        
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
            {
                txtDoctorID.setEditable(true);
            }
        else
            {
                txtDoctorID.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Doctor ID");
            }
    }//GEN-LAST:event_txtDoctorIDKeyPressed

    private void txtEducationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEducationKeyPressed
        // TODO add your handling code here:
        
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
            {
                txtEducation.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Education");
            }
        else
            {
                txtEducation.setEditable(true);
                
            }
    }//GEN-LAST:event_txtEducationKeyPressed

    private void txtSpecialityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpecialityKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
            {
                txtSpeciality.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Speciality");
            }
        else
            {
                txtSpeciality.setEditable(true);
                
            }
    }//GEN-LAST:event_txtSpecialityKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        int number = txtName.getCaretPosition();
        txtName.setText(txtName.getText().toUpperCase());
        txtName.setCaretPosition(number);
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEducationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEducationKeyReleased
        // TODO add your handling code here:
        int number = txtEducation.getCaretPosition();
        txtEducation.setText(txtEducation.getText().toUpperCase());
        txtEducation.setCaretPosition(number);
    }//GEN-LAST:event_txtEducationKeyReleased

    private void txtOfficeAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOfficeAddressKeyReleased
        // TODO add your handling code here:
        int number = txtOfficeAddress.getCaretPosition();
        txtOfficeAddress.setText(txtOfficeAddress.getText().toUpperCase());
        txtOfficeAddress.setCaretPosition(number);
    }//GEN-LAST:event_txtOfficeAddressKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblInsuranceCovered;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOfficeAddress;
    private javax.swing.JLabel lblOfficeHours;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtEducation;
    private javax.swing.JComboBox<String> txtInsuranceCovered;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOfficeAddress;
    private javax.swing.JComboBox<String> txtOfficeHours;
    private javax.swing.JTextField txtSpeciality;
    // End of variables declaration//GEN-END:variables
}
