/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author tanujamahajan
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    Patient patient;
    
    public CreatePatientJPanel(Patient patient) {
        initComponents();
        
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblDateOfLastVisitToDoctor = new javax.swing.JLabel();
        lblDateOfNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtAllergies = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        txtDateOfLastVisitToDoctor = new javax.swing.JTextField();
        txtDateOfNextAppointment = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Details");
        lblTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 51, 255), null));

        lblPatientID.setText("Patient ID:");

        lblPrimaryDoctor.setText("Primary Doctor:");

        lblDateOfLastVisitToDoctor.setText("Date Of Last Visit To Doctor:");

        lblDateOfNextAppointment.setText("Date Of Next Appointment:");

        lblAllergies.setText("Allergies:");

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        txtPatientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatientIDKeyPressed(evt);
            }
        });

        txtPrimaryDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryDoctorActionPerformed(evt);
            }
        });
        txtPrimaryDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrimaryDoctorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrimaryDoctorKeyReleased(evt);
            }
        });

        txtAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        txtAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergiesActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDateOfLastVisitToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfLastVisitToDoctorActionPerformed(evt);
            }
        });
        txtDateOfLastVisitToDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateOfLastVisitToDoctorKeyPressed(evt);
            }
        });

        txtDateOfNextAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfNextAppointmentActionPerformed(evt);
            }
        });
        txtDateOfNextAppointment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateOfNextAppointmentKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(lblPatientID))
                                .addComponent(lblPrimaryDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(lblAllergies)))
                            .addComponent(lblDateOfNextAppointment)
                            .addComponent(lblDateOfLastVisitToDoctor))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDateOfLastVisitToDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateOfNextAppointment)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(898, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrimaryDoctor))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfLastVisitToDoctor)
                    .addComponent(txtDateOfLastVisitToDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfNextAppointment)
                    .addComponent(txtDateOfNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllergies)
                    .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimaryDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryDoctorActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        patient.setPatientID(txtPatientID.getText());
        patient.setPrimaryDoctor(txtPrimaryDoctor.getText());
        patient.setDateOfLastVisitToDoctor(txtDateOfLastVisitToDoctor.getText());
        patient.setDateOfNextAppointment(txtDateOfNextAppointment.getText());
        patient.setAllergies(txtAllergies.getSelectedItem().toString());
                
                
        
        JOptionPane.showMessageDialog(this, "Patient Details Saved.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergiesActionPerformed

    private void txtPatientIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIDKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
        {
            txtPatientID.setEditable(true);
        }
        else
        {
            txtPatientID.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter a valid Patient ID");
            
        }
    }//GEN-LAST:event_txtPatientIDKeyPressed

    private void txtPrimaryDoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimaryDoctorKeyPressed
        // TODO add your handling code here:
        
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
        {
            txtPrimaryDoctor.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter a valid Primary Doctor");
        }
        else
        {
            txtPrimaryDoctor.setEditable(true);        
        }
    }//GEN-LAST:event_txtPrimaryDoctorKeyPressed

    private void txtDateOfLastVisitToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfLastVisitToDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfLastVisitToDoctorActionPerformed

    private void txtDateOfLastVisitToDoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateOfLastVisitToDoctorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfLastVisitToDoctorKeyPressed

    private void txtDateOfNextAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfNextAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfNextAppointmentActionPerformed

    private void txtDateOfNextAppointmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateOfNextAppointmentKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfNextAppointmentKeyPressed

    private void txtPrimaryDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimaryDoctorKeyReleased
        // TODO add your handling code here:
        int number = txtPrimaryDoctor.getCaretPosition();
        txtPrimaryDoctor.setText(txtPrimaryDoctor.getText().toUpperCase());
        txtPrimaryDoctor.setCaretPosition(number);
    }//GEN-LAST:event_txtPrimaryDoctorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblDateOfLastVisitToDoctor;
    private javax.swing.JLabel lblDateOfNextAppointment;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox<String> txtAllergies;
    private javax.swing.JTextField txtDateOfLastVisitToDoctor;
    private javax.swing.JTextField txtDateOfNextAppointment;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
