/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.VehicleRegistration;

/**
 *
 * @author tanujamahajan
 */
public class VehicleRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VehicleRegistrationJPanel
     */
    
    VehicleRegistration vehicle;
    
    public VehicleRegistrationJPanel(VehicleRegistration vehicle) {
        initComponents();
        this.vehicle = vehicle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVehicleRegistration = new javax.swing.JLabel();
        lblVIN = new javax.swing.JLabel();
        lblLicensePlateNumber = new javax.swing.JLabel();
        lblVehicleMakeandModel = new javax.swing.JLabel();
        lblVehicleType = new javax.swing.JLabel();
        lblYearofManufacture = new javax.swing.JLabel();
        txtVIN = new javax.swing.JTextField();
        txtLicensePlateNumber = new javax.swing.JTextField();
        txtYearofManufacture = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtMake = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        lblVehicleMakeandModel1 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));

        lblVehicleRegistration.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleRegistration.setText("Vehicle Registration Details");
        lblVehicleRegistration.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 51, 255), null));

        lblVIN.setText("VIN:");

        lblLicensePlateNumber.setText("License Plate Number");

        lblVehicleMakeandModel.setText("Vehicle Make:");

        lblVehicleType.setText("Vehicle Type:");

        lblYearofManufacture.setText("Year of Manufacture:");

        txtVIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVINKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVINKeyReleased(evt);
            }
        });

        txtLicensePlateNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLicensePlateNumberKeyPressed(evt);
            }
        });

        txtYearofManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearofManufactureActionPerformed(evt);
            }
        });
        txtYearofManufacture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearofManufactureKeyPressed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtMake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMakeKeyPressed(evt);
            }
        });

        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTypeKeyPressed(evt);
            }
        });

        lblVehicleMakeandModel1.setText("Vehicle Model:");

        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVehicleMakeandModel)
                            .addComponent(lblVIN)
                            .addComponent(lblLicensePlateNumber)
                            .addComponent(lblVehicleType)
                            .addComponent(lblYearofManufacture)
                            .addComponent(lblVehicleMakeandModel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtVIN, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(txtLicensePlateNumber)
                                .addComponent(txtYearofManufacture)
                                .addComponent(txtMake, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtType)
                                .addComponent(txtModel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblVehicleRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(940, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblVehicleRegistration)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVIN)
                    .addComponent(txtVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicensePlateNumber)
                    .addComponent(txtLicensePlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleMakeandModel)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleMakeandModel1)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleType)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYearofManufacture)
                    .addComponent(txtYearofManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(342, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        vehicle.setVehicleIdentificationNumber(txtVIN.getText());
        vehicle.setLicensePlateNumber(txtLicensePlateNumber.getText());
        vehicle.setVehicleMake(txtMake.getText());
        vehicle.setVehicleModel(txtModel.getText());
        vehicle.setVehicleType(txtType.getText());
        vehicle.setYearOfManufacture(txtYearofManufacture.getText());
        JOptionPane.showMessageDialog(this, "Vehicle Registration Details Saved.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtVINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVINKeyPressed
        // TODO add your handling code here:
        char name = evt.getKeyChar();
        if(Character.isDigit(name) || Character.isAlphabetic(name) )
        {
            txtVIN.setEditable(true);
        }
        else
        {
            txtVIN.setEditable(true);
            JOptionPane.showMessageDialog(this, "Please Enter Valid VIN.");
        }
    }//GEN-LAST:event_txtVINKeyPressed

    private void txtLicensePlateNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicensePlateNumberKeyPressed
        // TODO add your handling code here:
        char name = evt.getKeyChar();
        if(Character.isDigit(name) || Character.isAlphabetic(name) )
        {
            txtLicensePlateNumber.setEditable(true);
        }
        else
        {
            txtLicensePlateNumber.setEditable(true);
            JOptionPane.showMessageDialog(this, "Please Enter Valid License Plate Number.");
        }
    }//GEN-LAST:event_txtLicensePlateNumberKeyPressed

    private void txtMakeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMakeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                txtMake.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Vehicle Make");
            }
          else
          {
              txtMake.setEditable(true);
          }
    }//GEN-LAST:event_txtMakeKeyPressed

    private void txtTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                txtType.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Vehicle Type");
            }
          else
          {
              txtType.setEditable(true);
          }
    }//GEN-LAST:event_txtTypeKeyPressed

    private void txtModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                txtModel.setEditable(false);
                JOptionPane.showMessageDialog(this, "Enter a valid Vehicle Model");
            }
          else
          {
              txtModel.setEditable(true);
          }
    }//GEN-LAST:event_txtModelKeyPressed

    private void txtYearofManufactureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearofManufactureKeyPressed
        // TODO add your handling code here:
        String year = txtYearofManufacture.getText();
        int length = year.length();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                if(length<4)
                txtYearofManufacture.setEditable(true);
            }
          else
          {
              txtYearofManufacture.setEditable(false);
              JOptionPane.showMessageDialog(this, "Enter a year of manufacture");
          }
    }//GEN-LAST:event_txtYearofManufactureKeyPressed

    private void txtYearofManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearofManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearofManufactureActionPerformed

    private void txtVINKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVINKeyReleased
        // TODO add your handling code here:
        int number = txtVIN.getCaretPosition();
        txtVIN.setText(txtVIN.getText().toUpperCase());
        txtVIN.setCaretPosition(number);
    }//GEN-LAST:event_txtVINKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblLicensePlateNumber;
    private javax.swing.JLabel lblVIN;
    private javax.swing.JLabel lblVehicleMakeandModel;
    private javax.swing.JLabel lblVehicleMakeandModel1;
    private javax.swing.JLabel lblVehicleRegistration;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JLabel lblYearofManufacture;
    private javax.swing.JTextField txtLicensePlateNumber;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVIN;
    private javax.swing.JTextField txtYearofManufacture;
    // End of variables declaration//GEN-END:variables
}
